### ISSUE TITLE
Frequent exception raised in normal operation

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/obs_factory#102]
https://github.com/openSUSE/obs_factory/blob/05f616b0d2421a3fec4e6a741e14cd16f17b49c1/app/models/obs_factory/staging_project.rb#L116

osc staging adi calls this route using:

/project/staging_projects/openSUSE:Factory?format=json

Which in turn raises an exception, as there are multiple sub porjects (this was introduced when we switched to the overall state, instead of project wise - the exception is no longer valid)

**Comment by nilxam** [comment]
this should about https://github.com/openSUSE/osc-plugin-factory/issues/1102#issuecomment-325566518
