### ISSUE TITLE
Archive project and point to OBS

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/obs_factory#142]
Since this project was [merged into OBS](openSUSE/open-build-service/pull/5140) this project should be archived and the description/README updated to point people to OBS for filing new issues and pull requests.

**Comment by jberry-suse** [comment]
Archiving leaves all data accessible, just read-only. Also having a note pointing to OBS merge would be good.

**Comment by coolo** [comment]
but I guess I still want to erase HEAD - to shut up github security alerts :)

**Comment by jberry-suse** [comment]
> but I guess I still want to erase HEAD - to shut up github security alerts :)

Ah, well that I don't know about, but I would expect them to stop if archived since that indicates no longer maintained. Who knows.

**Comment by coolo** [comment]
Already tried that with teamdiary - it doesn't stop :(

**Comment by jberry-suse** [comment]
:(
