### ISSUE TITLE
Letter tab is missing when selected adi tab(Chrome 60)

### ISSUE THREAD

**Issue by nilxam** [openSUSE/obs_factory#91]
This issue is happened very recently, after clicked adi tab, Letter tab is missing from the tabbar.

![screenshot from 2017-07-31 20-44-23](https://user-images.githubusercontent.com/417859/28778366-857d0b20-7631-11e7-8abc-42d3dd863108.png)

**Comment by jberry-suse** [comment]
Hmm, cannot reproduce using chromium nor firefox.

**Comment by nilxam** [comment]
yup, I realized it only happened on chrome 60, tried on another machine upgrade from 59 to 60 confirmed that...

**Comment by jberry-suse** [comment]
Yep, updated chromium to 60 and indeed it vanishes.

**Comment by jberry-suse** [comment]
Seems the element is still there and toggling the `display: block` property brings it back. Interesting.

**Comment by jberry-suse** [comment]
If one disables the `.nav > input:first-child + section > h2 { position:relative }` the tabs both remain when clicked repeatedly although they do not change `z-index` properly. That seems to confirm the position/display bit being buggy in new version since toggling resolves.

**Comment by jberry-suse** [comment]
Seems to be fixed, not sure if OBS side or chromium 61.

**Comment by nilxam** [comment]
Could be fixed in chromium 61, this issue indeed disappeared on my chrome/chromium 61 but still presents on chrome 60, at least we know it does happened on chromium 60 only.
